import { useState } from "react";
import { useSupabaseClient } from "@supabase/auth-helpers-react";
import Layout from "../components/Layout.js";

export default function Page() {
  const supabase = useSupabaseClient();
  const [message, setMessage] = useState(null);
  const onSubmit = async function (e) {
    e.preventDefault();
    const data = new FormData(e.target);
    const { error } = await supabase
      .from("contacts")
      .insert(Object.fromEntries(data), { returning: "minimal" });
    if (error) {
      setMessage("Sorry, an unexpected error occured.");
    } else {
      setMessage(
        <div>
          <h2 className="text-center mt-3">Confirmation</h2>
          <p>Thank you for contacting us. We will get back to you promptly.</p>
        </div>
      );
    }
  };
  return (
    <Layout title="Contacts" description="Generated by create next app">
      <div className="bg-black text-white flex flex-col justify-center items-center" style={{ height: "70vh", width: "35vw" }}>
        <h1 className="wt-title">Contact us</h1>
        <div className="text-center mb-6 flex justify-center">
          <a href="#">
            <img
              src="/facebook.png"
              alt="Facebook"
              className="w-12 h-9 mx-2 my-1 cursor-pointer"
            />
          </a>
          <a href="#">
            <img
              src="/linkdin.png"
              alt="LinkedIn"
              className="w-8 h-8 mx-2 my-2 cursor-pointer"
            />
          </a>
          <a href="#">
            <img
              src="/Twitter.png"
              alt="Twitter"
              className="w-8 h-8 mx-2 my-2 cursor-pointer"
            />
          </a>
          <a href="#">
            <img
              src="/instagram.png"
              alt="Instagram"
              className="w-12 h-12 mx-2  cursor-pointer"
            />
          </a>
        </div>

        <form className="[&_span]:block grid gap-3" onSubmit={onSubmit}>
          <div>
            <label>
              <span>First name</span>
              <input type="text" name="firstname" />
            </label>
          </div>
          <div>
            <label>
              <span>Last name</span>
              <input type="text" name="lastname" />
            </label>
          </div>
          <div>
            <label>
              <span>Email</span>
              <input type="text" name="email" />
            </label>
          </div>
          <div>
            <label>
              <span>Message</span>
              <textarea name="message" />
            </label>
          </div>
          <div>
            <button className="rounded py-1 px-3 text-white bg-slate-500 hover:bg-blue-500">
              Submit
            </button>
          </div>
        </form>
        {message && (
          <div
            aria-label="Overlow below the drawer dialog"
            className="fixed inset-0 bg-black/80 flex items-center justify-center"
            onClick={() => setMessage(null)}
            role="dialog"
          >
            <div
              aria-label="Alert pane"
              className="max-h-[90vh] max-w-[95vw] overflow-auto p-4 prose bg-white"
            >
              {message}
            </div>
          </div>
        )}
      </div>
    </Layout>
  );
}
